/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file dot1qVlanStaticTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1QVLANSTATICTABLE_DATA_GET_H
#define DOT1QVLANSTATICTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1qVlanStaticTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * Q-BRIDGE-MIB::dot1qVlanStaticTable is subid 3 of dot1qVlan.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.7.1.4.3, length: 11
*/
    /*
     * indexes
     */
    int dot1qVlanIndex_map(u_long *mib_dot1qVlanIndex_val_ptr, u_long raw_dot1qVlanIndex_val);

    int dot1qVlanStaticName_get( dot1qVlanStaticTable_rowreq_ctx *rowreq_ctx, char **dot1qVlanStaticName_val_ptr_ptr, size_t *dot1qVlanStaticName_val_ptr_len_ptr );
    int dot1qVlanStaticEgressPorts_get( dot1qVlanStaticTable_rowreq_ctx *rowreq_ctx, char **dot1qVlanStaticEgressPorts_val_ptr_ptr, size_t *dot1qVlanStaticEgressPorts_val_ptr_len_ptr );
    int dot1qVlanForbiddenEgressPorts_get( dot1qVlanStaticTable_rowreq_ctx *rowreq_ctx, char **dot1qVlanForbiddenEgressPorts_val_ptr_ptr, size_t *dot1qVlanForbiddenEgressPorts_val_ptr_len_ptr );
    int dot1qVlanStaticUntaggedPorts_get( dot1qVlanStaticTable_rowreq_ctx *rowreq_ctx, char **dot1qVlanStaticUntaggedPorts_val_ptr_ptr, size_t *dot1qVlanStaticUntaggedPorts_val_ptr_len_ptr );
    int dot1qVlanStaticRowStatus_get( dot1qVlanStaticTable_rowreq_ctx *rowreq_ctx, u_long * dot1qVlanStaticRowStatus_val_ptr );


int dot1qVlanStaticTable_indexes_set_tbl_idx(dot1qVlanStaticTable_mib_index *tbl_idx, u_long dot1qVlanIndex_val);
int dot1qVlanStaticTable_indexes_set(dot1qVlanStaticTable_rowreq_ctx *rowreq_ctx, u_long dot1qVlanIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT1QVLANSTATICTABLE_DATA_GET_H */
/** @} */
