/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1QVLANSTATICTABLE_ENUMS_H
#define DOT1QVLANSTATICTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table dot1qVlanStaticTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * dot1qVlanStaticRowStatus (RowStatus / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef ROWSTATUS_ENUMS
#define ROWSTATUS_ENUMS

#define ROWSTATUS_ACTIVE  1 
#define ROWSTATUS_NOTINSERVICE  2 
#define ROWSTATUS_NOTREADY  3 
#define ROWSTATUS_CREATEANDGO  4 
#define ROWSTATUS_CREATEANDWAIT  5 
#define ROWSTATUS_DESTROY  6 

#endif /* ROWSTATUS_ENUMS */

    /*
     * TODO:140:o: Define your interal representation of dot1qVlanStaticRowStatus enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_DOT1QVLANSTATICTABLE_DOT1QVLANSTATICROWSTATUS_ACTIVE  1 
#define INTERNAL_DOT1QVLANSTATICTABLE_DOT1QVLANSTATICROWSTATUS_NOTINSERVICE  2 
#define INTERNAL_DOT1QVLANSTATICTABLE_DOT1QVLANSTATICROWSTATUS_NOTREADY  3 
#define INTERNAL_DOT1QVLANSTATICTABLE_DOT1QVLANSTATICROWSTATUS_CREATEANDGO  4 
#define INTERNAL_DOT1QVLANSTATICTABLE_DOT1QVLANSTATICROWSTATUS_CREATEANDWAIT  5 
#define INTERNAL_DOT1QVLANSTATICTABLE_DOT1QVLANSTATICROWSTATUS_DESTROY  6 




#ifdef __cplusplus
}
#endif

#endif /* DOT1QVLANSTATICTABLE_ENUMS_H */
