BRIDGE_MIB_SRCS += \
	dot1qVlanStaticTable/dot1qVlanStaticTable.c \
	dot1qVlanStaticTable/dot1qVlanStaticTable_data_get.c \
	dot1qVlanStaticTable/dot1qVlanStaticTable_data_set.c \
	dot1qVlanStaticTable/dot1qVlanStaticTable_data_access.c \
	dot1qVlanStaticTable/dot1qVlanStaticTable_interface.c
