/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef DOT1QFDBTABLE_H
#define DOT1QFDBTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(Q-BRIDGE-MIB)
config_require(Q-BRIDGE-MIB/dot1qFdbTable/dot1qFdbTable_interface)
config_require(Q-BRIDGE-MIB/dot1qFdbTable/dot1qFdbTable_data_access)
config_require(Q-BRIDGE-MIB/dot1qFdbTable/dot1qFdbTable_data_get)
config_require(Q-BRIDGE-MIB/dot1qFdbTable/dot1qFdbTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for dot1qFdbTable */
#include "dot1qFdbTable_oids.h"

/* enum definions */
#include "dot1qFdbTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_dot1qFdbTable(void);
void shutdown_dot1qFdbTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1qFdbTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * Q-BRIDGE-MIB::dot1qFdbTable is subid 1 of dot1qTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.7.1.2.1, length: 11
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dot1qFdbTable registration context.
     */
typedef netsnmp_data_list dot1qFdbTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dot1qFdbTable data context structure.
 * This structure is used to represent the data for dot1qFdbTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dot1qFdbTable.
 */
typedef struct dot1qFdbTable_data_s {
    
        /*
         * dot1qFdbDynamicCount(2)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
   u_long   dot1qFdbDynamicCount;
    
} dot1qFdbTable_data;


/*
 * TODO:120:r: |-> Review dot1qFdbTable mib index.
 * This structure is used to represent the index for dot1qFdbTable.
 */
typedef struct dot1qFdbTable_mib_index_s {

        /*
         * dot1qFdbId(1)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/r/d/h
         */
   u_long   dot1qFdbId;


} dot1qFdbTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dot1qFdbTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_dot1qFdbTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review dot1qFdbTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dot1qFdbTable_rowreq_ctx pointer.
 */
typedef struct dot1qFdbTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dot1qFdbTable_IDX_LEN];
    
    dot1qFdbTable_mib_index        tbl_idx;
    
    dot1qFdbTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to dot1qFdbTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dot1qFdbTable_data_list;

} dot1qFdbTable_rowreq_ctx;

typedef struct dot1qFdbTable_ref_rowreq_ctx_s {
    dot1qFdbTable_rowreq_ctx *rowreq_ctx;
} dot1qFdbTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dot1qFdbTable_pre_request(dot1qFdbTable_registration * user_context);
    int dot1qFdbTable_post_request(dot1qFdbTable_registration * user_context,
        int rc);

    int dot1qFdbTable_rowreq_ctx_init(dot1qFdbTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void dot1qFdbTable_rowreq_ctx_cleanup(dot1qFdbTable_rowreq_ctx *rowreq_ctx);


    dot1qFdbTable_rowreq_ctx *
                  dot1qFdbTable_row_find_by_mib_index(dot1qFdbTable_mib_index *mib_idx);

extern const oid dot1qFdbTable_oid[];
extern const int dot1qFdbTable_oid_size;


#include "dot1qFdbTable_interface.h"
#include "dot1qFdbTable_data_access.h"
#include "dot1qFdbTable_data_get.h"
#include "dot1qFdbTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DOT1QFDBTABLE_H */
/** @} */
