/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file dot1qFdbTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1QFDBTABLE_DATA_GET_H
#define DOT1QFDBTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1qFdbTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * Q-BRIDGE-MIB::dot1qFdbTable is subid 1 of dot1qTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.7.1.2.1, length: 11
*/
    /*
     * indexes
     */

    int dot1qFdbDynamicCount_get( dot1qFdbTable_rowreq_ctx *rowreq_ctx, u_long * dot1qFdbDynamicCount_val_ptr );


int dot1qFdbTable_indexes_set_tbl_idx(dot1qFdbTable_mib_index *tbl_idx, u_long dot1qFdbId_val);
int dot1qFdbTable_indexes_set(dot1qFdbTable_rowreq_ctx *rowreq_ctx, u_long dot1qFdbId_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT1QFDBTABLE_DATA_GET_H */
/** @} */
