BRIDGE_MIB_SRCS += \
	dot1qFdbTable/dot1qFdbTable.c \
	dot1qFdbTable/dot1qFdbTable_data_get.c \
	dot1qFdbTable/dot1qFdbTable_data_set.c \
	dot1qFdbTable/dot1qFdbTable_data_access.c \
	dot1qFdbTable/dot1qFdbTable_interface.c
