/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file dot1dStaticTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1DSTATICTABLE_DATA_GET_H
#define DOT1DSTATICTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStaticTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dStaticTable is subid 1 of dot1dStatic.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.5.1, length: 9
*/
    /*
     * indexes
     */
    int dot1dStaticAddress_map(char **mib_dot1dStaticAddress_val_ptr_ptr, size_t *mib_dot1dStaticAddress_val_ptr_len_ptr, char *raw_dot1dStaticAddress_val_ptr, size_t raw_dot1dStaticAddress_val_ptr_len, int allow_realloc);
    int dot1dStaticReceivePort_map(long *mib_dot1dStaticReceivePort_val_ptr, long raw_dot1dStaticReceivePort_val);

    int dot1dStaticAllowedToGoTo_map(char **mib_dot1dStaticAllowedToGoTo_val_ptr_ptr, size_t *mib_dot1dStaticAllowedToGoTo_val_ptr_len_ptr, char *raw_dot1dStaticAllowedToGoTo_val_ptr, size_t raw_dot1dStaticAllowedToGoTo_val_ptr_len, int allow_realloc);
    int dot1dStaticAllowedToGoTo_get( dot1dStaticTable_rowreq_ctx *rowreq_ctx, char **dot1dStaticAllowedToGoTo_val_ptr_ptr, size_t *dot1dStaticAllowedToGoTo_val_ptr_len_ptr );
    int dot1dStaticStatus_map(u_long *mib_dot1dStaticStatus_val_ptr, u_long raw_dot1dStaticStatus_val);
    int dot1dStaticStatus_get( dot1dStaticTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStaticStatus_val_ptr );


int dot1dStaticTable_indexes_set_tbl_idx(dot1dStaticTable_mib_index *tbl_idx, char *dot1dStaticAddress_val_ptr,  size_t dot1dStaticAddress_val_ptr_len, long dot1dStaticReceivePort_val);
int dot1dStaticTable_indexes_set(dot1dStaticTable_rowreq_ctx *rowreq_ctx, char *dot1dStaticAddress_val_ptr,  size_t dot1dStaticAddress_val_ptr_len, long dot1dStaticReceivePort_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTATICTABLE_DATA_GET_H */
/** @} */
