/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1DSTATICTABLE_OIDS_H
#define DOT1DSTATICTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot1dStaticTable */
#define DOT1DSTATICTABLE_OID              1,3,6,1,2,1,17,5,1


#define COLUMN_DOT1DSTATICADDRESS         1
#define COLUMN_DOT1DSTATICADDRESS_FLAG    (0x1 << 0)
    
#define COLUMN_DOT1DSTATICRECEIVEPORT         2
#define COLUMN_DOT1DSTATICRECEIVEPORT_FLAG    (0x1 << 1)
    
#define COLUMN_DOT1DSTATICALLOWEDTOGOTO         3
#define COLUMN_DOT1DSTATICALLOWEDTOGOTO_FLAG    (0x1 << 2)
    
#define COLUMN_DOT1DSTATICSTATUS         4
#define COLUMN_DOT1DSTATICSTATUS_FLAG    (0x1 << 3)
    

#define DOT1DSTATICTABLE_MIN_COL   COLUMN_DOT1DSTATICADDRESS
#define DOT1DSTATICTABLE_MAX_COL   COLUMN_DOT1DSTATICSTATUS
    


#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTATICTABLE_OIDS_H */
