BRIDGE_MIB_SRCS += \
	dot1dStaticTable/dot1dStaticTable.c \
	dot1dStaticTable/dot1dStaticTable_data_get.c \
	dot1dStaticTable/dot1dStaticTable_data_set.c \
	dot1dStaticTable/dot1dStaticTable_data_access.c \
	dot1dStaticTable/dot1dStaticTable_interface.c

