/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DOT1QTPFDBTABLE_INTERFACE_H
#define DOT1QTPFDBTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "dot1qTpFdbTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _dot1qTpFdbTable_initialize_interface(dot1qTpFdbTable_registration * user_ctx,
                                    u_long flags);
void _dot1qTpFdbTable_shutdown_interface(dot1qTpFdbTable_registration * user_ctx);

dot1qTpFdbTable_registration *
dot1qTpFdbTable_registration_get( void );

dot1qTpFdbTable_registration *
dot1qTpFdbTable_registration_set( dot1qTpFdbTable_registration * newreg );

netsnmp_container *dot1qTpFdbTable_container_get( void );
int dot1qTpFdbTable_container_size( void );

    dot1qTpFdbTable_rowreq_ctx * dot1qTpFdbTable_allocate_rowreq_ctx(void *);
void dot1qTpFdbTable_release_rowreq_ctx(dot1qTpFdbTable_rowreq_ctx *rowreq_ctx);

int dot1qTpFdbTable_index_to_oid(netsnmp_index *oid_idx,
                            dot1qTpFdbTable_mib_index *mib_idx);
int dot1qTpFdbTable_index_from_oid(netsnmp_index *oid_idx,
                              dot1qTpFdbTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void dot1qTpFdbTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* DOT1QTPFDBTABLE_INTERFACE_H */
/** @} */
