/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file dot1qTpFdbTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1QTPFDBTABLE_DATA_GET_H
#define DOT1QTPFDBTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1qTpFdbTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * Q-BRIDGE-MIB::dot1qTpFdbTable is subid 2 of dot1qTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.7.1.2.2, length: 11
*/
    /*
     * indexes
     */
    int dot1qFdbId_map(u_long *mib_dot1qFdbId_val_ptr, u_long raw_dot1qFdbId_val);
    int dot1qTpFdbAddress_map(char **mib_dot1qTpFdbAddress_val_ptr_ptr, size_t *mib_dot1qTpFdbAddress_val_ptr_len_ptr, char *raw_dot1qTpFdbAddress_val_ptr, size_t raw_dot1qTpFdbAddress_val_ptr_len, int allow_realloc);

    int dot1qTpFdbPort_map(long *mib_dot1qTpFdbPort_val_ptr, long raw_dot1qTpFdbPort_val);
    int dot1qTpFdbPort_get( dot1qTpFdbTable_rowreq_ctx *rowreq_ctx, long * dot1qTpFdbPort_val_ptr );
    int dot1qTpFdbStatus_map(u_long *mib_dot1qTpFdbStatus_val_ptr, u_long raw_dot1qTpFdbStatus_val);
    int dot1qTpFdbStatus_get( dot1qTpFdbTable_rowreq_ctx *rowreq_ctx, u_long * dot1qTpFdbStatus_val_ptr );


int dot1qTpFdbTable_indexes_set_tbl_idx(dot1qTpFdbTable_mib_index *tbl_idx, u_long dot1qFdbId_val, char *dot1qTpFdbAddress_val_ptr,  size_t dot1qTpFdbAddress_val_ptr_len);
int dot1qTpFdbTable_indexes_set(dot1qTpFdbTable_rowreq_ctx *rowreq_ctx, u_long dot1qFdbId_val, char *dot1qTpFdbAddress_val_ptr,  size_t dot1qTpFdbAddress_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* DOT1QTPFDBTABLE_DATA_GET_H */
/** @} */
