/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1QTPFDBTABLE_OIDS_H
#define DOT1QTPFDBTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot1qTpFdbTable */
#define DOT1QTPFDBTABLE_OID              1,3,6,1,2,1,17,7,1,2,2


#define COLUMN_DOT1QTPFDBADDRESS         1
    
#define COLUMN_DOT1QTPFDBPORT         2
    
#define COLUMN_DOT1QTPFDBSTATUS         3
    

#define DOT1QTPFDBTABLE_MIN_COL   COLUMN_DOT1QTPFDBPORT
#define DOT1QTPFDBTABLE_MAX_COL   COLUMN_DOT1QTPFDBSTATUS
    


#ifdef __cplusplus
}
#endif

#endif /* DOT1QTPFDBTABLE_OIDS_H */
