BRIDGE_MIB_SRCS += \
	dot1qTpFdbTable/dot1qTpFdbTable.c \
	dot1qTpFdbTable/dot1qTpFdbTable_data_get.c \
	dot1qTpFdbTable/dot1qTpFdbTable_data_set.c \
	dot1qTpFdbTable/dot1qTpFdbTable_data_access.c \
	dot1qTpFdbTable/dot1qTpFdbTable_interface.c

