/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DOT1QVLANCURRENTTABLE_INTERFACE_H
#define DOT1QVLANCURRENTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "dot1qVlanCurrentTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _dot1qVlanCurrentTable_initialize_interface(dot1qVlanCurrentTable_registration * user_ctx,
                                    u_long flags);
void _dot1qVlanCurrentTable_shutdown_interface(dot1qVlanCurrentTable_registration * user_ctx);

dot1qVlanCurrentTable_registration *
dot1qVlanCurrentTable_registration_get( void );

dot1qVlanCurrentTable_registration *
dot1qVlanCurrentTable_registration_set( dot1qVlanCurrentTable_registration * newreg );

netsnmp_container *dot1qVlanCurrentTable_container_get( void );
int dot1qVlanCurrentTable_container_size( void );

    dot1qVlanCurrentTable_rowreq_ctx * dot1qVlanCurrentTable_allocate_rowreq_ctx(void *);
void dot1qVlanCurrentTable_release_rowreq_ctx(dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx);

int dot1qVlanCurrentTable_index_to_oid(netsnmp_index *oid_idx,
                            dot1qVlanCurrentTable_mib_index *mib_idx);
int dot1qVlanCurrentTable_index_from_oid(netsnmp_index *oid_idx,
                              dot1qVlanCurrentTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void dot1qVlanCurrentTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* DOT1QVLANCURRENTTABLE_INTERFACE_H */
/** @} */
