/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file dot1qVlanCurrentTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1QVLANCURRENTTABLE_DATA_GET_H
#define DOT1QVLANCURRENTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1qVlanCurrentTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * Q-BRIDGE-MIB::dot1qVlanCurrentTable is subid 2 of dot1qVlan.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.7.1.4.2, length: 11
*/
    /*
     * indexes
     */
    int dot1qVlanFdbId_get( dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx, u_long * dot1qVlanFdbId_val_ptr );
    int dot1qVlanCurrentEgressPorts_get( dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx, char **dot1qVlanCurrentEgressPorts_val_ptr_ptr, size_t *dot1qVlanCurrentEgressPorts_val_ptr_len_ptr );
    int dot1qVlanCurrentUntaggedPorts_get( dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx, char **dot1qVlanCurrentUntaggedPorts_val_ptr_ptr, size_t *dot1qVlanCurrentUntaggedPorts_val_ptr_len_ptr );
    int dot1qVlanStatus_get( dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx, u_long * dot1qVlanStatus_val_ptr );
    int dot1qVlanCreationTime_get( dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx, u_long * dot1qVlanCreationTime_val_ptr );


int dot1qVlanCurrentTable_indexes_set_tbl_idx(dot1qVlanCurrentTable_mib_index *tbl_idx, u_long dot1qVlanTimeMark_val, u_long dot1qVlanIndex_val);
int dot1qVlanCurrentTable_indexes_set(dot1qVlanCurrentTable_rowreq_ctx *rowreq_ctx, u_long dot1qVlanTimeMark_val, u_long dot1qVlanIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT1QVLANCURRENTTABLE_DATA_GET_H */
/** @} */
