/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1QVLANCURRENTTABLE_ENUMS_H
#define DOT1QVLANCURRENTTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table dot1qVlanCurrentTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * dot1qVlanStatus (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef DOT1QVLANSTATUS_ENUMS
#define DOT1QVLANSTATUS_ENUMS

#define DOT1QVLANSTATUS_OTHER  1 
#define DOT1QVLANSTATUS_PERMANENT  2 
#define DOT1QVLANSTATUS_DYNAMICGVRP  3 

#endif /* DOT1QVLANSTATUS_ENUMS */

    /*
     * TODO:140:o: Define your interal representation of dot1qVlanStatus enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_DOT1QVLANCURRENTTABLE_DOT1QVLANSTATUS_OTHER  1 
#define INTERNAL_DOT1QVLANCURRENTTABLE_DOT1QVLANSTATUS_PERMANENT  2 
#define INTERNAL_DOT1QVLANCURRENTTABLE_DOT1QVLANSTATUS_DYNAMICGVRP  3 




#ifdef __cplusplus
}
#endif

#endif /* DOT1QVLANCURRENTTABLE_ENUMS_H */
