/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1QVLANCURRENTTABLE_OIDS_H
#define DOT1QVLANCURRENTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot1qVlanCurrentTable */
#define DOT1QVLANCURRENTTABLE_OID              1,3,6,1,2,1,17,7,1,4,2


#define COLUMN_DOT1QVLANTIMEMARK         1
    
#define COLUMN_DOT1QVLANINDEX         2
    
#define COLUMN_DOT1QVLANFDBID         3
    
#define COLUMN_DOT1QVLANCURRENTEGRESSPORTS         4
    
#define COLUMN_DOT1QVLANCURRENTUNTAGGEDPORTS         5
    
#define COLUMN_DOT1QVLANSTATUS         6
    
#define COLUMN_DOT1QVLANCREATIONTIME         7
    

#define DOT1QVLANCURRENTTABLE_MIN_COL   COLUMN_DOT1QVLANFDBID
#define DOT1QVLANCURRENTTABLE_MAX_COL   COLUMN_DOT1QVLANCREATIONTIME
    


#ifdef __cplusplus
}
#endif

#endif /* DOT1QVLANCURRENTTABLE_OIDS_H */
