BRIDGE_MIB_SRCS += \
	dot1qVlanCurrentTable/dot1qVlanCurrentTable.c \
	dot1qVlanCurrentTable/dot1qVlanCurrentTable_data_get.c \
	dot1qVlanCurrentTable/dot1qVlanCurrentTable_data_set.c \
	dot1qVlanCurrentTable/dot1qVlanCurrentTable_data_access.c \
	dot1qVlanCurrentTable/dot1qVlanCurrentTable_interface.c
