#!/bin/sh

# This script applies the dot-config. It is a boot script, but actual
# functionality is moved to a separate binary, so the web interface
# could edit dot-config and run /wr/bin/apply_dot-config like we do here,
# without the need to rember wheter this is S20 or S10 during boot.

# First, read dot-config to get the new location, if any.
dotconfig=/wr/etc/dot-config
tmpconfig=/tmp/dot-config
dot_config_overwrite_file=/update/permanent/dot-config/dot-config-overwrite
tmpdir=/tmp
log_output=/dev/kmsg
management_port=eth0
me=`basename "$0"`

set -o pipefail # The return value of a pipeline is the status of
                # the last command to exit with a non-zero status,
                # or zero if no command exited with a non-zero status
                # Needed for return value ($?) of xxx in "xxx | tee yyy"

#
# This function is looping forever until DHCP is reachable 
#
wait_dhcp_forever()
{
	while  : ; do
		udhcpc -n -q  -i $management_port
		if [ "$?" -eq "0" ]; then
			break
		fi
		echo "$me: waiting DHCP service (press ENTER to abandon) ...."
		# wait for input for 5s, timeout if no input.
		read -t 5
		# any input will result in the returned value to be zero
		if [ "$?" -eq "0" ]; then
			# report to log that something went wrong
			echo "WARNING: Obtaining dot-config source URL from "\
			     "DHCP service was abandoned by the user."\
			     | tee $log_output  >& 2
			return 1
		fi
	done
}

dot_config_overwrite()
{
	dot_config_file=$1
	tmpconfig_local=/tmp/dot-config_local
	# Check if overwrite is enabled, grep local or received file
	DOTCONF_LOCAL_OVERWRITE=`grep -e '^CONFIG_DOTCONF_LOCAL_OVERWRITE' $dot_config_file | sed 's/CONFIG_DOTCONF_LOCAL_OVERWRITE=\(.*\)/\1/'`
	if [ "$DOTCONF_LOCAL_OVERWRITE" != "y" ]; then
		echo "CONFIG_DOTCONF_LOCAL_OVERWRITE disabled" | tee $log_output >& 2
		return
	fi
	echo "CONFIG_DOTCONF_LOCAL_OVERWRITE enabled" | tee $log_output >& 2
	if [ ! -f $dot_config_overwrite_file ]; then
		echo "Dot-config overwrite: $dot_config_overwrite_file file not found!" | tee $log_output >& 2
		return
	fi
	echo "Dot-config overwrite: Using $dot_config_overwrite_file with content:" | tee $log_output >& 2
	cat $dot_config_overwrite_file | tee $log_output >& 2
	cp "$dot_config_file" $tmpconfig_local
	cat $dot_config_overwrite_file >> $tmpconfig_local
	save_pwd=$PWD
	cd /wr/etc/
	echo "Overwritten/new configuration items:" | tee $log_output >& 2
	# KCONFIG_OVERWRITECONFIG=y - replace file in place
	# KCONFIG_CONFIG - dot-config location
	# -s - silent
	KCONFIG_OVERWRITECONFIG=y KCONFIG_CONFIG=$tmpconfig_local ./conf --listnewconfig Kconfig 2>&1 | tee $log_output >& 2
	KCONFIG_OVERWRITECONFIG=y KCONFIG_CONFIG=$tmpconfig_local ./conf -s --olddefconfig Kconfig 2>&1 | tee $log_output >& 2
	cd $save_pwd

	# Update file in /update only when the content is different (to avoid wear-out of flash)
	if ! cmp -s $tmpconfig_local $dot_config_file; then
		echo "Dot-config overwrite: New config is different. Replacing the old one." | tee $log_output >& 2
		cp $tmpconfig_local $dot_config_file
	else
		echo "Dot-config overwrite: New dot-config is the same as the old one." | tee $log_output >& 2
	fi
}

rm -f "$tmpdir"/dot-config_source

if [ -f $dotconfig ]; then
    # source dot-config
    . $dotconfig
    ret_source=$?
    /wr/bin/wrs_checkcfg $dotconfig /wr/etc/Kconfig 2>&1| tee $log_output
    ret_check=$?
    if [ $ret_source != 0 ] || [ $ret_check != 0 ]; then
	# errors in local dot-config
	echo "check_error" > "$tmpdir"/dot-config_status
	echo "Errors found in local dot-config!!!" | tee $log_output >& 2
    else
	echo "config_ok" > "$tmpdir"/dot-config_status
    fi
else
    echo "No /wr/etc/dot-config to use" | tee $log_output >& 2
    echo "no_config" > "$tmpdir"/dot-config_source
    echo "config_error" > "$tmpdir"/dot-config_status
fi

# Create /etc/resolv.conf, so we can use it. /etc is ramdisk anyways
if [ ! -z "$CONFIG_DNS_SERVER" ]; then
    echo "nameserver $CONFIG_DNS_SERVER" > /etc/resolv.conf
    if [ ! -z "$CONFIG_DNS_DOMAIN" ]; then
        echo "domain $CONFIG_DNS_DOMAIN" >> /etc/resolv.conf
    fi
fi

# remove "$tmpdir"/dot-config_source_url" in case it is not first run
# of this script
rm -f "$tmpdir"/dot-config_source_url

# If we are expected to get a new dot-conf, do it
if [ "$CONFIG_DOTCONF_SOURCE_REMOTE" = "y" ] || [ "$CONFIG_DOTCONF_SOURCE_TRY_DHCP" = "y" ] \
	|| [ "$CONFIG_DOTCONF_SOURCE_FORCE_DHCP" = "y" ]; then
    echo "remote" > "$tmpdir"/dot-config_source

    # get URL via DHCP
    if [ "$CONFIG_DOTCONF_SOURCE_TRY_DHCP" = "y" ] \
	    || [ "$CONFIG_DOTCONF_SOURCE_FORCE_DHCP" = "y" ]; then
		if [ "$CONFIG_DOTCONF_SOURCE_TRY_DHCP" = "y" ]; then
		    echo "try_dhcp" > "$tmpdir"/dot-config_source
		fi
		if [ "$CONFIG_DOTCONF_SOURCE_FORCE_DHCP" = "y" ]; then
		    echo "force_dhcp" > "$tmpdir"/dot-config_source
		fi
	
		# up management port to allow dhcp requests
		ifconfig $management_port up
		if [ "$CONFIG_DOTCONF_SOURCE_FORCE_DHCP" = "y" ] && [ "$CONFIG_ETH0_DHCP" = "y" ]; then
			# Wait DHCP forever only if DHCP is also forced on management port  
		    wait_dhcp_forever
		    # check whether the DHCP loop was abandoned by the user (return 1)
		    if [ "$?" -eq "1" ]; then
		       # no DHCP, complain properly and apply the local/old dot-config
		       echo "dhcp_error" > "$tmpdir"/dot-config_status
		       echo "Unable to get dot-config's URL via DHCP, using old dot-config"\
		            | tee $log_output >& 2
		       # Error, using local dot-config, but check check if the overwrite is needed
		       dot_config_overwrite $dotconfig
		       # apply old dot-config
		       /wr/bin/apply_dot-config
		       exit
		    fi
		fi
		# let udhcpc run /wr/bin/dhcp_get_filename.sh script to get "filename"
		# from DHCP (which contain url with dot-config).
		/sbin/udhcpc -i $management_port -s /wr/bin/dhcp_get_filename.sh -O bootfile -O hostname -o \
			-n -q -f -t 5 &>/dev/null
		if [ -f "$tmpdir"/dot-config_source_url ]; then
		    # replace CONFIG_DOTCONF_URL with one gotten from dhcp
		    CONFIG_DOTCONF_URL=`cat "$tmpdir"/dot-config_source_url`
		    echo "Got dot-config's URL ("$CONFIG_DOTCONF_URL") via DHCP" | tee $log_output >& 2
		else
		    echo "dhcp_error" > "$tmpdir"/dot-config_status
		    echo "Unable to get dot-config's URL via DHCP, using old dot-config" | tee $log_output >& 2
		    # Error, using local dot-config, but check check if the overwrite is needed
		    dot_config_overwrite $dotconfig
		    # apply old dot-config
		    /wr/bin/apply_dot-config
		    exit
		fi
    fi

    # replace IPADDR and MACADDR, to have a device-specific name
    macaddr=$(cat /sys/class/net/${management_port}/address)
    ipaddr=$(ifconfig ${management_port} | grep inet | cut -d: -f 2 | cut '-d '  -f 1)
    if [ -z "$ipaddr" ]; then
		# if no IP address available from barebox try to get IP from old dot-config
		# /etc/init.d/network will run later again
		/etc/init.d/network
		ipaddr=$(ifconfig ${management_port} | grep inet | cut -d: -f 2 | cut '-d '  -f 1)
    fi
    host_name=`hostname`
    URL=$(echo $CONFIG_DOTCONF_URL | \
	sed -e s/MACADDR/$macaddr/g -e s/IPADDR/$ipaddr/g -e s/HOSTNAME/$host_name/g)
    # split the parts, as we need to handle tftp by hand
    proto=$(echo $URL | cut -d: -f 1)
    host=$(echo $URL | cut -d/ -f 3)
    filename=$(echo $URL | cut -d/ -f 4-)

    # save URL of dot-config, to be used by SNMPd
    echo "$URL" > "$tmpdir"/dot-config_source_url
    rm -f $tmpconfig
    case $proto in
		http|https|ftp)
		    wget --no-check-certificate $URL -O $tmpconfig
		    ;;
		tftp)
		    tftp -g -r "$filename" -l $tmpconfig $host
		    ;;
		*)
		    echo "Invalid URL for dot-config: \"$URL\"" | tee $log_output >& 2
		    ;;
    esac
    if [ -f $tmpconfig ]; then
		# If it exists, it is not empty or too small and the checker is happy
		# then try to source it in another shell to verify syntax
		if [ $(cat $tmpconfig | wc -c) -gt 200 ] &&
		    /wr/bin/wrs_checkcfg $tmpconfig /wr/etc/Kconfig 2>&1| tee $log_output &&
		    /bin/sh -c ". $tmpconfig"; then
		    echo "Using newly-downloaded dot-config from $URL" | tee $log_output >& 2
		    # Using downloaded dot-config, apply overwrite if needed
		    dot_config_overwrite $tmpconfig
		    # copy it in place to use the new file (unless it is identical)
		    cmp -s $tmpconfig $dotconfig || cp $tmpconfig $dotconfig
		    # info for SNMP that downloading was successful and checker is happy
		    echo "config_ok" > "$tmpdir"/dot-config_status
		    # Finally, apply new dot-config
		    /wr/bin/apply_dot-config
		    exit
		else
		    echo "check_error" > "$tmpdir"/dot-config_status
		    echo "Errors found in downloaded dot-config \"$URL\", using old" | tee $log_output >& 2
		fi
    else
		echo "download_error" > "$tmpdir"/dot-config_status
		echo "Download error for dot-config \"$URL\", using old" | tee $log_output >& 2
    fi
elif [ "$CONFIG_DOTCONF_SOURCE_LOCAL" = "y" ]; then
    echo "local" > "$tmpdir"/dot-config_source
    echo "Using local dot-config" | tee $log_output >& 2
else
    echo "Unknown dot-config source. Using local dot-config" | tee $log_output >& 2
fi

# Error or not, using local dot-config, check if the overwrite is needed
dot_config_overwrite $dotconfig

# Finally, apply what we have, be it old or new
/wr/bin/apply_dot-config
