BRIDGE_MIB_SRCS += \
	dot1dBasePortTable/dot1dBasePortTable.c \
	dot1dBasePortTable/dot1dBasePortTable_data_get.c \
	dot1dBasePortTable/dot1dBasePortTable_data_set.c \
	dot1dBasePortTable/dot1dBasePortTable_data_access.c \
	dot1dBasePortTable/dot1dBasePortTable_interface.c

