/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef DOT1QPORTVLANTABLE_H
#define DOT1QPORTVLANTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(Q-BRIDGE-MIB)
config_require(Q-BRIDGE-MIB/dot1qPortVlanTable/dot1qPortVlanTable_interface)
config_require(Q-BRIDGE-MIB/dot1qPortVlanTable/dot1qPortVlanTable_data_access)
config_require(Q-BRIDGE-MIB/dot1qPortVlanTable/dot1qPortVlanTable_data_get)
config_require(Q-BRIDGE-MIB/dot1qPortVlanTable/dot1qPortVlanTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for dot1qPortVlanTable */
#include "dot1qPortVlanTable_oids.h"

/* enum definions */
#include "dot1qPortVlanTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_dot1qPortVlanTable(void);
void shutdown_dot1qPortVlanTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1qPortVlanTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * Q-BRIDGE-MIB::dot1qPortVlanTable is subid 5 of dot1qVlan.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.7.1.4.5, length: 11
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dot1qPortVlanTable registration context.
     */
typedef netsnmp_data_list dot1qPortVlanTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dot1qPortVlanTable data context structure.
 * This structure is used to represent the data for dot1qPortVlanTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dot1qPortVlanTable.
 */
typedef struct dot1qPortVlanTable_data_s {
    
        /*
         * dot1qPvid(1)/VlanIndex/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/H
         */
   u_long   dot1qPvid;
    
        /*
         * dot1qPortAcceptableFrameTypes(2)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   dot1qPortAcceptableFrameTypes;
    
        /*
         * dot1qPortIngressFiltering(3)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   dot1qPortIngressFiltering;
    
        /*
         * dot1qPortGvrpStatus(4)/EnabledStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   dot1qPortGvrpStatus;
    
        /*
         * dot1qPortGvrpFailedRegistrations(5)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
   u_long   dot1qPortGvrpFailedRegistrations;
    
        /*
         * dot1qPortGvrpLastPduOrigin(6)/MacAddress/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   dot1qPortGvrpLastPduOrigin[6];
size_t      dot1qPortGvrpLastPduOrigin_len; /* # of char elements, not bytes */
    
        /*
         * dot1qPortRestrictedVlanRegistration(7)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
         */
   u_long   dot1qPortRestrictedVlanRegistration;
    
} dot1qPortVlanTable_data;


/*
 * TODO:120:r: |-> Review dot1qPortVlanTable mib index.
 * This structure is used to represent the index for dot1qPortVlanTable.
 */
typedef struct dot1qPortVlanTable_mib_index_s {

        /*
         * dot1dBasePort(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   dot1dBasePort;


} dot1qPortVlanTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dot1qPortVlanTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_dot1qPortVlanTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review dot1qPortVlanTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dot1qPortVlanTable_rowreq_ctx pointer.
 */
typedef struct dot1qPortVlanTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dot1qPortVlanTable_IDX_LEN];
    
    dot1qPortVlanTable_mib_index        tbl_idx;
    
    dot1qPortVlanTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to dot1qPortVlanTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dot1qPortVlanTable_data_list;

} dot1qPortVlanTable_rowreq_ctx;

typedef struct dot1qPortVlanTable_ref_rowreq_ctx_s {
    dot1qPortVlanTable_rowreq_ctx *rowreq_ctx;
} dot1qPortVlanTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dot1qPortVlanTable_pre_request(dot1qPortVlanTable_registration * user_context);
    int dot1qPortVlanTable_post_request(dot1qPortVlanTable_registration * user_context,
        int rc);

    int dot1qPortVlanTable_rowreq_ctx_init(dot1qPortVlanTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void dot1qPortVlanTable_rowreq_ctx_cleanup(dot1qPortVlanTable_rowreq_ctx *rowreq_ctx);


    dot1qPortVlanTable_rowreq_ctx *
                  dot1qPortVlanTable_row_find_by_mib_index(dot1qPortVlanTable_mib_index *mib_idx);

extern const oid dot1qPortVlanTable_oid[];
extern const int dot1qPortVlanTable_oid_size;


#include "dot1qPortVlanTable_interface.h"
#include "dot1qPortVlanTable_data_access.h"
#include "dot1qPortVlanTable_data_get.h"
#include "dot1qPortVlanTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DOT1QPORTVLANTABLE_H */
/** @} */
