/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1QPORTVLANTABLE_ENUMS_H
#define DOT1QPORTVLANTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table dot1qPortVlanTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * dot1qPortAcceptableFrameTypes (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef DOT1QPORTACCEPTABLEFRAMETYPES_ENUMS
#define DOT1QPORTACCEPTABLEFRAMETYPES_ENUMS

#define DOT1QPORTACCEPTABLEFRAMETYPES_ADMITALL  1 
#define DOT1QPORTACCEPTABLEFRAMETYPES_ADMITONLYVLANTAGGED  2 

#endif /* DOT1QPORTACCEPTABLEFRAMETYPES_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * dot1qPortIngressFiltering (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * dot1qPortGvrpStatus (EnabledStatus / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef ENABLEDSTATUS_ENUMS
#define ENABLEDSTATUS_ENUMS

#define ENABLEDSTATUS_ENABLED  1 
#define ENABLEDSTATUS_DISABLED  2 

#endif /* ENABLEDSTATUS_ENUMS */

/*************************************************************
 * constants for enums for the MIB node
 * dot1qPortRestrictedVlanRegistration (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 

#endif /* TRUTHVALUE_ENUMS */

#ifdef __cplusplus
}
#endif

#endif /* DOT1QPORTVLANTABLE_ENUMS_H */
