BRIDGE_MIB_SRCS += \
	dot1qPortVlanTable/dot1qPortVlanTable.c \
	dot1qPortVlanTable/dot1qPortVlanTable_data_get.c \
	dot1qPortVlanTable/dot1qPortVlanTable_data_set.c \
	dot1qPortVlanTable/dot1qPortVlanTable_data_access.c \
	dot1qPortVlanTable/dot1qPortVlanTable_interface.c
