/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DOT1QBASE_H
#define DOT1QBASE_H

#define DOT1QVLANVERSIONNUMBER 1

#define DOT1QGVRPSTATUS_ENABLED  1
#define DOT1QGVRPSTATUS_DISABLED 2

/* function declarations */
void init_dot1qBase(void);
Netsnmp_Node_Handler handle_dot1qVlanVersionNumber;
Netsnmp_Node_Handler handle_dot1qMaxVlanId;
Netsnmp_Node_Handler handle_dot1qMaxSupportedVlans;
Netsnmp_Node_Handler handle_dot1qNumVlans;
Netsnmp_Node_Handler handle_dot1qGvrpStatus;

#endif /* DOT1QBASE_H */
