/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DOT1DBASE_H
#define DOT1DBASE_H

/* Defines */
#define BASETYPE_UNKNOWN            1
#define BASETYPE_TRANSPARENT_ONLY   2
#define BASETYPE_SOURCEROUTE_ONLY   3
#define BASETYPE_SRT                4

#define FIRST_PORT_NAME "wri1"

/* function declarations */
void init_dot1dBase(void);
Netsnmp_Node_Handler handle_dot1dBaseBridgeAddress;
Netsnmp_Node_Handler handle_dot1dBaseNumPorts;
Netsnmp_Node_Handler handle_dot1dBaseType;

#endif /* DOT1DBASE_H */
