BRIDGE_MIB_SRCS += \
	dot1dTpFdbTable/dot1dTpFdbTable.c \
	dot1dTpFdbTable/dot1dTpFdbTable_data_get.c \
	dot1dTpFdbTable/dot1dTpFdbTable_data_set.c \
	dot1dTpFdbTable/dot1dTpFdbTable_data_access.c \
	dot1dTpFdbTable/dot1dTpFdbTable_interface.c

