check process crond matching /usr/sbin/crond
   start program = "/etc/init.d/cron.sh start"
   stop program = "/etc/init.d/cron.sh stop"
   if 5 restarts within 10 cycles then exec "/etc/init.d/reboot.sh crond"
