 check process radiusvlan matching /wr/bin/radiusvlan
   start program = "/etc/init.d/radiusvlan.sh start"
   stop program = "/etc/init.d/radiusvlan.sh stop"
   if 5 restarts within 10 cycles then exec "/etc/init.d/reboot.sh radiusvlan"
